const BOT=/(gptbot|chatgpt|claudebot|anthropic|perplexitybot|amazonbot|bytespider|ccbot|google-extended|applebot-extended|duckassistbot|cohere-ai|meta-externalagent|bot|crawl|spider|scraper|preview|http-client|curl|wget|python-requests|python-urllib|node-fetch|okhttp)/i;async function sign(keyStr,msg){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(keyStr),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(msg));return Array.from(new Uint8Array(sig)).map(b=>b.toString(16).padStart(2,'0')).join('').slice(0,16);}
function _clean(v){return(v||'').replace(/[\x00-\x1f\x7f]/g,'').trim();}
function _shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));const t=a[i];a[i]=a[j];a[j]=t;}
return a;}
function _allowed(dest,nodes,refUrl,siteHost){let p;try{p=new URL(dest);}catch(_){return false;}
if(p.protocol!=='https:')return false;const host=p.hostname.toLowerCase();const forbidden=[siteHost.toLowerCase()];for(const n of nodes){try{forbidden.push(new URL(n).hostname.toLowerCase());}catch(_){}}
try{if(refUrl)forbidden.push(new URL(refUrl).hostname.toLowerCase());}catch(_){}
for(const bad of forbidden){if(bad&&(host===bad||host.endsWith('.'+bad)))return false;}
return true;}
async function _askNode(url,headers,timeoutMs){const ctl=new AbortController();const timer=setTimeout(()=>ctl.abort(),timeoutMs);let resp;try{resp=await fetch(url,{method:'GET',redirect:'manual',headers,signal:ctl.signal});}catch(_){throw{next:!ctl.signal.aborted};}finally{clearTimeout(timer);}
const s=resp.status;if(s===521||s===522||s===523||s===525||s===526)throw{next:true};const loc=resp.headers.get('location')||'';if(s<300||s>399||!loc)throw{next:false};return{location:loc,cookie:resp.headers.get('x-uniqueness-cookie')||'',maxAge:parseInt(resp.headers.get('x-cookie-max-age')||'0',10)||0,};}
function _unavailable(){return new Response('<!doctype html><meta charset="utf-8"><title>Please try again</title>'
+'<p style="font:16px/1.5 system-ui;margin:3rem auto;max-width:30rem;text-align:center">'
+'This link is temporarily unavailable. Please try again in a minute.</p>',{status:503,headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store'}});}
export default{async fetch(request,env){const url=new URL(request.url);const path=url.pathname;const nf=async()=>{try{const r=await env.ASSETS.fetch(new URL('/404.html',request.url).toString());return new Response(r.body,{status:404,headers:r.headers});}catch(_){return new Response('Not Found',{status:404});}};if(path==='/wrangler.jsonc'||path==='/_gate.js')return nf();if(env.UMAMI_COLLECTOR){if(path==='/app.js'){let base='';try{const a=await env.ASSETS.fetch(new URL('/app.js',request.url).toString());if(a&&a.ok)base=await a.text();}catch(_){}
const beacon="\n(function(){var e=document.currentScript;"+"if(!e)return;var w=e.getAttribute('data-cid');if(!w)return;"+"var S=screen,L=location;try{fetch('/api/send',{method:'POST',"+"keepalive:true,headers:{'content-type':'application/json'},"+"body:JSON.stringify({type:'event',payload:{website:w,"+"hostname:L.hostname,screen:S.width+'x'+S.height,"+"language:navigator.language,title:document.title,"+"url:L.pathname+L.search,referrer:document.referrer}})})"+".catch(function(){});}catch(_){}})();\n";return new Response(base+beacon,{headers:{'content-type':'application/javascript; charset=utf-8','cache-control':'public, max-age=3600',}});}
if(path==='/api/send'){const h=new Headers(request.headers);const ip=request.headers.get('CF-Connecting-IP');if(ip)h.set('X-Client-IP',ip);h.delete('CF-Connecting-IP');return fetch('https://'+env.UMAMI_COLLECTOR+'/api/send',{method:request.method,headers:h,body:request.body,});}}
const ua=(request.headers.get('user-agent')||'').toLowerCase();const cookieName=env.COOKIE_NAME;const tokenPath=env.TOKEN_PATH?'/'+env.TOKEN_PATH:'';let playMap={};try{playMap=JSON.parse(env.PLAY_MAP||'{}');}catch(_){}
if(tokenPath&&(path===tokenPath||path===tokenPath+'/')){if(BOT.test(ua))return nf();const sfs=request.headers.get('sec-fetch-site');if(sfs&&sfs!=='same-origin'&&sfs!=='same-site')return nf();if(!cookieName||!env.HMAC_KEY)return nf();const ts=String(Math.floor(Date.now()/1000));const sig=await sign(env.HMAC_KEY,ts);return new Response('',{status:204,headers:{'Set-Cookie':cookieName+'='+ts+'.'+sig
+'; Path=/; SameSite=Strict; Max-Age=30; Secure','Cache-Control':'no-store',},});}
const slug=path.replace(/^\/+|\/+$/g,'');if(slug&&Object.prototype.hasOwnProperty.call(playMap,slug)){if(BOT.test(ua))return nf();const sfd=request.headers.get('sec-fetch-dest');if(sfd&&sfd!=='document')return nf();const sfs=request.headers.get('sec-fetch-site');if(sfs&&sfs!=='same-origin'&&sfs!=='same-site')return nf();if(!cookieName||!env.HMAC_KEY)return nf();const m=(request.headers.get('cookie')||'').match(new RegExp('(?:^|;\\s*)'+cookieName+'=([^;]+)'));if(!m)return nf();const[tsStr,sigHex]=m[1].split('.');const ts=parseInt(tsStr,10);const now=Math.floor(Date.now()/1000);if(!Number.isFinite(ts)||!sigHex||(now-ts)>30||(now-ts)<-5){return nf();}
const expected=await sign(env.HMAC_KEY,tsStr);if(sigHex!==expected)return nf();const refUrl=playMap[slug];if(!refUrl)return nf();let nodes;try{nodes=JSON.parse(env.GO_URLS||'[]');}catch(_){nodes=[];}
if(!Array.isArray(nodes)||!nodes.length)return _unavailable();const qs=new URLSearchParams();for(const[k,v]of url.searchParams){if(/^(utm_[a-z_]+|sub_id_\d+)$/.test(k))qs.set(k,v);}
const suffix=qs.toString()?('?'+qs.toString()):'';const goCookie=env.GO_COOKIE||'';const cookieHdr=request.headers.get('cookie')||'';const gc=goCookie?cookieHdr.match(new RegExp('(?:^|;\\s*)'+goCookie+'=([^;]+)')):null;const siteHost=url.hostname.replace(/^www\./,'');const headers={};const put=(n,val)=>{const c=_clean(val);if(c)headers[n]=c;};put('X-Request-Token',env.GO_TOKEN);put('X-Request-Ref',refUrl);put('X-Request-Site',siteHost);put('X-Visitor-IP',request.headers.get('CF-Connecting-IP'));put('X-Visitor-UA',request.headers.get('user-agent'));put('X-Visitor-Lang',(request.headers.get('accept-language')||'').slice(0,5));put('X-Visitor-Country',request.headers.get('CF-IPCountry'));put('X-Visitor-Cookie',gc?gc[1]:'');put('X-Visitor-Referer',request.headers.get('referer'));let answer=null;for(const node of _shuffle(nodes.slice())){try{answer=await _askNode(node+suffix,headers,9000);break;}catch(e){if(e&&e.next)continue;return _unavailable();}}
if(!answer||!_allowed(answer.location,nodes,refUrl,siteHost)){return _unavailable();}
const respHeaders={'content-type':'text/html; charset=utf-8','cache-control':'no-store, private',};if(goCookie&&answer.cookie){const secs=answer.maxAge>0?answer.maxAge:86400;respHeaders['set-cookie']=goCookie+'='+answer.cookie
+'; Path=/; Max-Age='+secs+'; Secure; HttpOnly; SameSite=Lax';}
const target=answer.location;const jsUrl=JSON.stringify(target);const htmlUrl=target.replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;');const html='<!doctype html><meta charset="utf-8">'
+'<meta name="referrer" content="no-referrer">'
+'<meta http-equiv="refresh" content="0;url='+htmlUrl+'">'
+'<script>location.replace('+jsUrl+')</script>';return new Response(html,{status:200,headers:respHeaders});}
return env.ASSETS.fetch(request);},};